Repository 36-APPJAM-HEARTZ/BYEBOO-iOS, pull requests merged in 2025-09, with the labels that each got.

#231 [Feat] 닉네임 수정 뷰 진입 시 키보드 애니메이션 추가
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/ModifyNicknameViewController.swift
Labels: 승준🤠, feat

#234 [Fix] UI 문제 자체 QA
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuitModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/WriteQuestionTypeQuestViewController.swift
Labels: 승준🤠, fix

#236 Fix/#224 홈 탭 이슈 해결
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Home/HomeHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewController/HomeViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Tutorial/TutorialModalViewController.swift
Labels: 주리🐿️, fix

#235 Feat/#223 오프보딩 플로우 연결
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserQuestStatusResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/QuestAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestsRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/ProgressingQuestsEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewController/HomeViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewModel/HomeViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/NewJourneySelectViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewModel/NewJourneyViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewController/FinishJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Coordinator/QuestCheckCoordinating.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Coordinator/QuestCheckCoordinator.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestStartViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewModel/QuestStartViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/ViewControllerFactory.swift
Labels: 주리🐿️, feat

#238 Feat/#218 자동로그인 및 토큰 재발급
  ByeBoo-iOS/ByeBoo-iOS/App/SceneDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/PostLoginResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/TokenReissueResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Persistence/Service/KeychainManager.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Persistence/UserDefaultsKey.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/AuthRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/AuthInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/AutoLoginUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/TokenReissueUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Login/View/SplashView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Login/ViewController/LoginViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Login/ViewController/SplashViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Login/ViewModel/LoginViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Login/ViewModel/SplashViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/ViewControllerFactory.swift
Labels: 나연🐹, feat

#239 [Feat] 완료된 여정 전체 퀘스트 돌아보기 API 연동
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/CompletedQuestsResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/QuestAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestsRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/CompletedQuestsEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/ProgressingQuestsEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/QuestsInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/FetchCompletedQuestsUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/LookBackJourneyView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/LookBackJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/View/CompletedQuestsHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewController/CompletedQuestsViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewModel/CompletedQuestsViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Common/QuestHeaderBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Common/ViewAllQuestBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestMain/QuestCheckHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/ViewControllerFactory.swift
Labels: 승준🤠, feat

#244 [Fix] 자체 QA
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/Common/InformationBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/ModifyNicknameViewController.swift
Labels: 승준🤠, fix

#249 Fix/#225 자잘한 UI 이슈
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/LookBackJourneyResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserJourneyResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/JourneyEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ViewControllerUtils.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Enum/HomeState+Presentation.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewController/HomeViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/NewJourneySelectViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/View/FinishJourneyView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewController/FinishJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewModel/FinishJourneyViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestStartViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/CongratSquare.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/ViewControllerFactory.swift
Labels: 주리🐿️, fix

#251 Fix/#246 9/3자 1차 QA 반영
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageFeatureView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/ViewController/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/ViewModel/CompletedQuestsViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/TermsView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/ViewController/TermsViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Common/ViewAllQuestBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStart/QuestStartView.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/world_second.imageset/world_second.svg
Labels: 승준🤠, fix

#273 Refactor/#271 2차 QA 반영(승준)
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/ProgressingQuestsEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/String+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageFeatureView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/Archive/ArchiveQuestHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStart/QuestStartView.swift
Labels: 승준🤠, refactor
