Repository 36-APPJAM-HEARTZ/BYEBOO-iOS, pull requests merged in 2025-07, with the labels that each got.

#10 Setting/#5 dicontainer 세팅
  ByeBoo-iOS/ByeBoo-iOS/App/DIContainer+.swift
  ByeBoo-iOS/ByeBoo-iOS/App/SceneDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Core/DIContainer.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/DataDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/TestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
Labels: 주리🐿️, setting

#24 Setting/#23 base extension 세팅
  ByeBoo-iOS/ByeBoo-iOS.xcodeproj/project.pbxproj
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Base/BaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Base/BaseViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UIStackView+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UIView+.swift
Labels: 주리🐿️, setting

#31 Style/#20 닉네임 텍스트필드 컴포넌트 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooNicknameTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/String+.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/IconSystem/error_red.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/IconSystem/error_red.imageset/icon.svg
Labels: 승준🤠, feat, style

#35 Style/#28 공통 모달 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CongrateModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CustomModalController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/ModalBuilder.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/ModalProtocol.swift
Labels: 주리🐿️, feat, style

#36 Style/#34 top navigation bar
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooNavigationBar.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooNicknameTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/BackNavigable.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/Dismissible.swift
Labels: 승준🤠, feat, style

#37 Feat/#16 네트워크 코드 세팅
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooError.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/BaseResponse.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/EndPoint.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/HomeAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/TestRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/TestInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/TestUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CustomModalController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewModel/TestViewModel.swift
Labels: 주리🐿️, setting

#39 style/#33 quit modal 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CongrateModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CustomModalController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuitModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/ModalProtocol.swift
Labels: 나연🐹, style

#44 Style/#43 마이페이지 UI 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/SectionDividerView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/TextBoxView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyRecordView.swift
Labels: 주리🐿️, style

#40 Style/#38 퀘스트 모달 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuestModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UIButton+.swift
Labels: 승준🤠, feat, style

#48 Feat/#41 닉네임 입력 뷰 구현
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooNicknameTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuestModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/BottomNavigationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/ByeBooNavigationBar.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/String+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/InformationBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/ProgressBarView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewType.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InputNicknameView.swift
Labels: 승준🤠, feat, style

#52 [Hotfix] 빌드 오류 해결을 위한 빈 파일 추가
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/SelectEmotionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/SelectQuestView.swift
Labels: 승준🤠, hotfix

#50 Setting/#45 저장된 퀘스트 다시보기
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ArchiveQuestHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/OneLineTextBoxView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/TextBoxView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/FeelView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ThinkView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyRecordView.swift
Labels: 주리🐿️, style

#54 Feat/#49 select emotion
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooNicknameTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/ByeBooNavigationBar.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/InformationBaseView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/InformationViewType.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Emotion/EmotionCardView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Emotion/EmotionCardsView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Emotion/SelectEmotionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Nickname/InputNicknameView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Quest/SelectQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/SelectEmotionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/good.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/good.imageset/good.png
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/sad.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/sad.imageset/sad.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/soso.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/soso.imageset/soso.png
Labels: 승준🤠, feat, style

#62 Style/#61 FilledTag enum 수정
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooFilledTag.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/EmotionBottomSheet/EmotionChip.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Quest/WriteQuestTitleView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
Labels: 나연🐹, style

#64 Style/#59 마무리 UI
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooError.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UILabel+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/FinishJourney/View/FinishJourneyView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/FinishJourney/View/FinishJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/NewJourneySelectViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestInitView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestInitViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestSelectCard.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/completeJourney.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/completeJourney.imageset/completeJourney.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/newJourney.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/newJourney.imageset/newJourney.svg
Labels: 주리🐿️, style

#69 Style/#63 행동형 퀘스트 UI
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooFilledTag.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/ImagePickerContainer.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/QuestTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/WriteQuestTitleView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/QuestCompleteProtocol.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Info.plist
Labels: 나연🐹, style

#72 Style/#65 홈 초기 UI
  ByeBoo-iOS/ByeBoo-iOS.xcodeproj/project.pbxproj
  ByeBoo-iOS/ByeBoo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ByeBoo-iOS/ByeBoo-iOS/App/SceneDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CustomModalController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/OnboardingTextView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/FinishJourney/View/FinishJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeStateView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/JourneyProgressView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/JourneyResultView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/JourneyResultViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestInitViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/faceEmotion.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/faceEmotion.imageset/faceEmotion.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/processEmotion.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/processEmotion.imageset/processEmotion.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/speechBubble.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/speechBubble.imageset/Group 2085669531.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Lottie/Bori_home_4.json
Labels: 주리🐿️, style

#78 Refactor/#77 모달 백그라운드 터치 이벤트 추가
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CustomModalController.swift
Labels: 주리🐿️, refactor

#73 Style/#70 퀘스트 팁 조회 UI 구현
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/QuestTipResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestTipRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/QuestTipEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/QuestTipInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/QuestTipUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooYellowTag.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/IconOneLineTextView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewModel/QuestTipViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/WriteQuestTitleView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/TipTagDidTapProtocol.swift
Labels: 나연🐹, style

#75 Feat/#67 로딩 화면 구현
  ByeBoo-iOS/ByeBoo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/Extension/EmotionState+.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserRequestDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/Enum/EmotionState.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/Enum/QuestStyle.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/UserEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/ByeBooNavigationBar.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/String+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/ProgressBarView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Emotion/SelectEmotionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Loading/LoadingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Loading/LoadingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Quest/SelectQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/ViewModel/InformationViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Lottie/Loading_byeboo.json
Labels: 승준🤠, feat, style

#84 Style/#82 온보딩
  ByeBoo-iOS/ByeBoo-iOS/App/SceneDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooButton.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/View/FinishJourneyView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Offboarding/View/FinishJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/OnboardingContentView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/OnboardingHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/OnboardingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/OnboardingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/fifth.imageset/5th.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/fifth.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/first.imageset/1st.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/first.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/fourth.imageset/4th.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/fourth.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/second.imageset/2nd.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/second.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/third.imageset/3rd.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Onboarding/third.imageset/Contents.json
Labels: 주리🐿️, style

#89 Feat/#85 api 세팅 userdefaults 등록 로직
  ByeBoo-iOS/ByeBoo-iOS.xcodeproj/project.pbxproj
  ByeBoo-iOS/ByeBoo-iOS/App/SceneDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooError.swift
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooLogger.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/DataDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserJourneyResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/EndPoint.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/UsersAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Persistence/Service/UserDefaultService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Persistence/UserDefaultsKey.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/UsersRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/JourneyEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/UsersInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/FetchUserJourneyUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/GetUserNameUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/JourneyResultView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/JourneyResultViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewModel/JourneyResultViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Loading/LoadingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Info.plist
Labels: 주리🐿️, setting

#92 Feat/#91 유저 정보 저장 API 연동 및 유저 이름 로드
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooError.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/Extension/Encodable+.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/Extension/Feeling+.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserRequestDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/UserResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/UsersAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/UsersRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/Enum/Feeling.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/UserEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/UsersInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/SendUserUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Feeling/EmotionCardView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Feeling/EmotionCardsView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Feeling/SelectEmotionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/ViewModel/InformationViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Onboarding/View/OnboardingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
Labels: 승준🤠, feat

#99 Fix/#96 퀘스트 전체 조회 UI 레이아웃 문제 해결
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/SectionDividerView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Feeling/EmotionCardView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Quest/QuestCardView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/Common/CollectionViewFactory.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStateCell.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestsCheckView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QusetStepHeaderView.swift
Labels: 승준🤠, fix

#101 Feat/#94 홈 api
  ByeBoo-iOS/ByeBoo-iOS/Core/ByeBooError.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/CompleteQuestCountResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/DialogueResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/HomeAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/UsersAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Persistence/Service/UserDefaultService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/UsersRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/UsersInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/FetchCharacterDialogueUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/FetchCompleteQuestCountUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/StartJourneyUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/BottomNavigationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/OnboardingTextView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeStateView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/JourneyProgressView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/ViewModel/HomeViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/JourneyListView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/LookBackJourneyView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/LookBackJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/NewJourneySelectView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/NewJourneySelectViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStartViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewModel/QuestStartViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
Labels: 주리🐿️, feat

#105 Feat/#98 질문형 퀘스트 저장 및 조회 API 연결
  ByeBoo-iOS/ByeBoo-iOS/Data/DataDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/QuestAnswerResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/SaveQuestRequestDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/QuestAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestAnswerRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/SaveQuestTypeRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/QuestAnswerInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/SaveQuestTypeInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/QuestAnswerUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/SaveQuestTypeUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooFilledTag.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/EmotionBottomSheet/EmotionBottomSheetViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Enum/ByeBooEmotion.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/FeelView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/CongratSquare.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/QuestTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/WriteQuestTitleView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/ViewModel/CompleteQuestViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/ViewModel/WriteQuestTypeViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Protocol/BottomSheetProtocol.swift
Labels: 나연🐹, feat

#107 Fix/#103 flick 현상 해결
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/BottomNavigationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Loading/LoadingViewController.swift
Labels: 주리🐿️, fix

#109 Feat/#106 팁 조회 API 구현
  ByeBoo-iOS/ByeBoo-iOS/Data/DataDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/QuestTipResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestAnswerRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/QuestTipRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Entity/QuestTipEntity.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/QuestAnswerInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/QuestTipInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/QuestAnswerUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/QuestTipUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewModel/QuestTipViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/ViewModel/WriteQuestTypeViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
Labels: 나연🐹, feat

#113 Feat/#98 행동형 퀘스트 저장 API 연동
  ByeBoo-iOS/ByeBoo-iOS/Data/DataDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/SaveQuestActiveRequestDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/SignedURLRequestDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Model/SignedURLResponseDTO.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/EndPoint/QuestAPI.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Network/Service/NetworkService.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/GetQuestInfoRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/SaveQuestActiveRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/Interface/SaveQuestActiveInterface.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/UseCase/SaveQuestActiveUseCase.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/ViewModel/WriteActiveTypeViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/PresentationDependencyAssembler.swift
Labels: 나연🐹, feat

#124 Feat/#121 퀘스트 작성 파트 내비게이션 구현
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/GetQuestInfoRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Data/Repository/SaveQuestActiveRepository.swift
  ByeBoo-iOS/ByeBoo-iOS/Domain/DomainDependencyAssembler.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ArchiveQuestHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuestModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UIApplication+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ActionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/FeelView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ThinkView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStateCell.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
Labels: 승준🤠, feat

#126 Feat/#123 아카이브 뷰 바인딩
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ArchiveQuestHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ByeBooFilledTag.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/EmotionBottomSheet/EmotionChip.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/TextBoxView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ActionView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/FeelView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ThinkView.swift
Labels: 나연🐹, feat

#129 docs/#128 리드미 작성
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ActionView.swift
  README.md
Labels: 나연🐹, docs

#137 Fix/#136 1차 qa
  ByeBoo-iOS/ByeBoo-iOS/App/AppDelegate.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/CustomLoadingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/HomeStateView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/JourneyProgressView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/HomeOnboardingViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/MyPageViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/AppIcon.appiconset/AppLogo.png
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/AppIcon.appiconset/appIcon.png
Labels: 주리🐿️, fix

#138 Fix/#135 1차 QA 반영
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/ArchiveQuestHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/EmotionBottomSheet/EmotionBottomSheetViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/CongrateModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuestModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuitModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/TextBoxView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/QuestTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/WriteQuestTitleView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
Labels: 나연🐹, fix

#141 Fix/#134 QA 반영
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/CustomLoadingView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Modal/QuestModalView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/Navigation/ByeBooNavigationBar.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/ArchiveQuest/View/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Common/ProgressBarView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Feeling/EmotionCardsView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/InformationViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Nickname/InputNicknameView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Information/View/Quest/QuestCardsView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/LookBackJourneyViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/MyPage/View/NewJourneySelectViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestStateCell.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QuestTipViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/View/QusetStepHeaderView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/QuestionType/View/WriteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/good.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/good.imageset/good.png
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/good.imageset/good.svg
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/soso.imageset/Contents.json
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/soso.imageset/soso.png
  ByeBoo-iOS/ByeBoo-iOS/Resource/Assets.xcassets/Bori/soso.imageset/soso.svg
Labels: 승준🤠, fix

#143 Fix/#142 태그 텍스트 잘리는 오류 수정
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Common/OnboardingTextView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UICollectionReusableView+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Extension/UIFont+.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ActivationType/View/WriteActiveTypeQuestView.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/Common/QuestTextField.swift
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-Bold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-ExtraBold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-ExtraLight.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-Light.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-Medium.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-Regular.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-SemiBold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/Pretendard-Thin.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Bold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-ExtraBold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-ExtraLight.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Heavy.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Light.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Medium.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Regular.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-SemiBold.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Font/SUIT-Thin.otf
  ByeBoo-iOS/ByeBoo-iOS/Resource/Info.plist
Labels: 나연🐹, fix

#155 Fix/#154 자꾸만 잔상이 남아
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/ArchiveQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewController/QuestCheckViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Quest/ViewModel/QuestsViewModel.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteActiveTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewController/CompleteQuestionTypeQuestViewController.swift
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/WriteQuest/ViewModel/CompleteQuestViewModel.swift
Labels: 주리🐿️, fix

#159 Fix/#158 오타 수정
  ByeBoo-iOS/ByeBoo-iOS/Presentation/Feature/Home/View/Onboarding/OnboardingContentView.swift
Labels: 주리🐿️, fix
